// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
	"github.com/pocketbase/pocketbase/models"
	"github.com/pocketbase/pocketbase/tools/types"
)

// Posts is a wrapper around models.Record for type safe operations on the collection posts.
type Posts struct {
	Record *models.Record
}

// GetText returns the value of the "text" field
func (m *Posts) GetText() string {
	return m.Record.GetString("text")
}

// SetText sets the value of the "text" field
func (m *Posts) SetText(val string) {
	m.Record.Set("text", val)
}

// GetEditor returns the value of the "editor" field as HTML
func (m *Posts) GetEditor() string {
	return m.Record.GetString("editor")
}

// SetEditor sets the value of the "editor" field as HTML
func (m *Posts) SetEditor(val string) {
	m.Record.Set("editor", val)
}

// GetNumberA returns the value of the "number_a" field
func (m *Posts) GetNumberA() int {
	return m.Record.GetInt("number_a")
}

// SetNumberA sets the value of the "number_a" field
func (m *Posts) SetNumberA(val int) {
	m.Record.Set("number_a", val)
}

// GetBool returns the value of the "bool" field
func (m *Posts) GetBool() bool {
	return m.Record.GetBool("bool")
}

// SetBool sets the value of the "bool" field
func (m *Posts) SetBool(val bool) {
	m.Record.Set("bool", val)
}

// GetEmail returns the value of the "email" field as email
func (m *Posts) GetEmail() string {
	return m.Record.GetString("email")
}

// SetEmail sets the value of the "email" field as email
func (m *Posts) SetEmail(val string) {
	m.Record.Set("email", val)
}

// GetUrl returns the value of the "url" field as URL
func (m *Posts) GetUrl() string {
	return m.Record.GetString("url")
}

// SetUrl sets the value of the "url" field as URL
func (m *Posts) SetUrl(val string) {
	m.Record.Set("url", val)
}

// GetDatetime returns the value of the "datetime" field
func (m *Posts) GetDatetime() types.DateTime {
	return m.Record.GetDateTime("datetime")
}

// SetDatetime sets the value of the "datetime" field
func (m *Posts) SetDatetime(val types.DateTime) {
	m.Record.Set("datetime", val)
}

// GetSelectSingle returns the value of the "select_single" field
// Possible values: [a b c]
func (m *Posts) GetSelectSingle() string {
	return m.Record.GetString("select_single")
}

// SetSelectSingle sets the value of the "select_single" field
// Possible values: [a b c]
func (m *Posts) SetSelectSingle(val string) {
	m.Record.Set("select_single", val)
}

// GetSelectMultiple returns the value of the "select_multiple" field
// Possible values: [d e f a]
func (m *Posts) GetSelectMultiple() []string {
	return m.Record.GetStringSlice("select_multiple")
}

// SetSelectMultiple sets the value of the "select_multiple" field
// Possible values: [d e f a]
func (m *Posts) SetSelectMultiple(val []string) {
	m.Record.Set("select_multiple", val)
}

// GetFileSingle returns the value of the "file_single" field as file
func (m *Posts) GetFileSingle() string {
	return m.Record.GetString("file_single")
}

// SetFileSingle sets the value of the "file_single" field as file
func (m *Posts) SetFileSingle(val string) {
	m.Record.Set("file_single", val)
}

// GetFileMultiple returns the value of the "file_multiple" field as file
func (m *Posts) GetFileMultiple() []string {
	return m.Record.GetStringSlice("file_multiple")
}

// SetFileMultiple sets the value of the "file_multiple" field as file
func (m *Posts) SetFileMultiple(val []string) {
	m.Record.Set("file_multiple", val)
}

// GetOwner returns the value of the "owner" field
// Relation collection related : _pb_users_auth_
func (m *Posts) GetOwner() string {
	return m.Record.GetString("owner")
}

// SetOwner sets the value of the "owner" field
// Relation collection related : _pb_users_auth_
func (m *Posts) SetOwner(val string) {
	m.Record.Set("owner", val)
}

// GetOwners returns the value of the "owners" field
// Relation collection related : _pb_users_auth_
func (m *Posts) GetOwners() []string {
	return m.Record.GetStringSlice("owners")
}

// SetOwners sets the value of the "owners" field
// Relation collection related : _pb_users_auth_
func (m *Posts) SetOwners(val []string) {
	m.Record.Set("owners", val)
}

// GetJson returns the value of the "json" field
func (m *Posts) GetJson() types.JsonRaw {
	return m.Record.Get("json").(types.JsonRaw)
}

// SetJson sets the value of the "json" field
func (m *Posts) SetJson(val types.JsonRaw) {
	m.Record.Set("json", val)
}
