// Code generated by pb-codegen v0.1 DO NOT EDIT.
package modelspb

import (
	"github.com/pocketbase/pocketbase/models"
)

// Users is a wrapper around models.Record for type safe operations on the collection users.
type Users struct {
	Record *models.Record
}

// GetName returns the value of the "name" field
func (m *Users) GetName() string {
	return m.Record.GetString("name")
}

// SetName sets the value of the "name" field
func (m *Users) SetName(val string) {
	m.Record.Set("name", val)
}

// GetAvatar returns the value of the "avatar" field as file
func (m *Users) GetAvatar() string {
	return m.Record.GetString("avatar")
}

// SetAvatar sets the value of the "avatar" field as file
func (m *Users) SetAvatar(val string) {
	m.Record.Set("avatar", val)
}

// GetDiscordUsername returns the value of the "discord_username" field
func (m *Users) GetDiscordUsername() string {
	return m.Record.GetString("discord_username")
}

// SetDiscordUsername sets the value of the "discord_username" field
func (m *Users) SetDiscordUsername(val string) {
	m.Record.Set("discord_username", val)
}
